

source('../R/utils.R')
source('../R/create_marker_files.R')
source("../R/sel_rep_replicates_create_dist_matrix.R")

## required by sel_rep_replicates_create_dist_matrix.R
source('../R/subject.R')
source('../R/distance_distribution_heatmap.R')

## required by subject.R
source("../R/create_JSM_matrix.R")
source("../R/select_representative_replicates.R")
source("../R/get_overlap_scores.R")
source("../R/create_overview_table_dist_to_normal.R")
source("../R/distance_distribution_plot.R")
source("../R/write_distance_matrices.R")
source("../R/plot_overlap_scores.R")




library(polyG)
setwd('~/lab_repos/polyG_pipeline/example')

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# create marker files for each poly-G marker in each sample
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

create_marker_files(sample_table_file='raw_data/C57sample_table.csv',peak_table_file='raw_data/C57peak_table.csv',markers_file='raw_data/Markers.txt',mixes_file='raw_data/Mixes.txt',sizing_artifacts_file='raw_data/SizingArtifacts.txt',pdir='.',genemapper=F,overwrite=T)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# select representative replicates and create distance matrices
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sel_rep_replicates_create_dist_matrix(subject_name='C57',sel_normal_sample='C57N1',all_normal_samples=c('C57N1'),pdir='.',sample_exclusion_th=0.15,max_replicate_th=0.11,overwrite=T,sample_name_change=T)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# create phylogenetic trees with bootstrap values
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

source('~/lab_repos/polyG_pipeline/R/create_phylogenetic_trees_with_bootstrap_values.R')
source('~/lab_repos/polyG_pipeline/R/phylogenetic_tree_with_boostrap_sampleNameChange.R')

create_phylogenetic_trees_with_bootstrap_values(subject_name='C57',sel_normal_sample='C57N1',all_normal_samples=c('C57N1'),pdir='.',overwrite=T,sample_exclusion_th=0.15,max_replicate_th=0.11,sample_name_change=T,colorfile_header=F)






# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# original polyG main.R 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### This script is used to analyze poly-G data. 
### Requires: 
### 1. polygR folder of R scripts in direcoty "pdir" 
### 2. for each patient, all sample names in "patient" + "_SampleNames.txt" in directory "pdir/sample_names"
### 3. for each patient, in directory "wdir":
###    (a) sample table file in "file_prefix" + "sample_table.csv"
###    (b) peak table file in "file_prefix" + "peak_table.csv"
###    (c) marker region definition in "Markers.txt"
###    (d) mix definition in "Mixes.txt"
###    (e) "SizingArtifacts.txt" if "sizingartifacts" is TRUE
### 4. A file in directory "pdir/colorfiles" for tree tip colors with filename of the form of "patient" + "_colorfile.txt" (e.g., E18_colorfile.txt)
### 5. A file in directory "pdir/AnnotationFiles" with filename of the form of "patient" + "_annotationFile.txt") (e.g., E1_annotationFile.txt) if new sample names would be used in the phylogenetic tree
###    The annotation files should contain two columns with column names. The first column should be the original sample names and the second column the new sample names.. 

# install required packages as needed
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("phyloseq")
BiocManager::install("gplots")
BiocManager::install("RColorBrewer")
BiocManager::install("dendextend")
BiocManager::install("ape")
BiocManager::install("phangorn")
BiocManager::install("adephylo")

# load the packages
library(phyloseq)
library(gplots)
library(RColorBrewer)
library(colorspace)
library(dendextend)
library(ape)
library(phangorn)

# the folder containing the entire polygR folder
# the folder containing the entire polygR folder
pdir <- "/Users/emma/Dropbox/Naxerova_lab/polyg_analysis_R - EW"

## create marker files from peak table
wdir <- "/Users/emma/Dropbox/Naxerova_lab/project peritoneal metastases/LEGO MmC1"

# Were the sample table and peak table generated by Genemapper?
genemapper <- TRUE

# Name of peak and sample files
file_prefix <- "MmC1"

if (genemapper==TRUE) {
  source(paste0(pdir,"/polygR/create_marker_files_genemapper.R"))
} else {
  source(paste0(pdir,"/polygR/create_marker_files.R"))
}


## select representative replicates and create distance matrices and heatmaps
max_replicate_th <- 0.11

# a parameter related to insertion/deletion calls
rob_th <- 0.05

# plot trees during the bootstrapping process if desired
plot_bootstrpping_tree <- FALSE
if (plot_bootstrpping_tree) {
  # number of trees to plot
  ntrees <- 50
}
# plot angular distance trees during the bootstrapping process if desired
plot_bootstrpping_ad_tree <- FALSE
# number of ad_trees to plot during bootstrapping if desired
ntrees_ad <- 50

# colorfile has column names or not? (TRUE if yes, FALSE if no)
colorfile_header <- TRUE

# samples excluded if no rep. replicates for more than this fraction of markers 
sample_exclusion_th <- 0.15

# here you can adjust the stringency of the purity exclusion.
# this will not change the values but only the decision whether to exclude or not

lm_slope_cutoff <- 0.35

# exclude impure samples for KLM? (TRUE if impure samples from "Purity_Estimation_for_polygR_w_distCutoff.R" are to be excluded.)
pexclude <- FALSE

# bootstrap cutoff below which clades are collapsed (for KLM script)
bscut <- 50

# plotting heatmaps and trees with different sample names from those in the marker files? 
sample_name_change <- TRUE

# maximum number of normal samples
nnormals <- 3

# ready for KLM?
KLM <- FALSE

# ready for KLM for angular distance tree?
KLM_ad <- FALSE

paper_primary_tumor_label <- "PT"
paper_normal_sample_label <- "Normal"

# power used for angular distance, original: power = 1
power <- 1

treetypes <- c("NJ","UPGMA")

# get data for a subject

data_path <- "E1-Data"

source(paste0(pdir,"/polygR/sel_rep_replicates_create_dist_matrix.R"))


## create phylogenetic trees with bootstrap values

# put the name of your normal reference sample here
ref <- sel_normal_sample

if (sample_name_change) {  
  source(paste0(pdir,"/polygR/phylogenetic_tree_with_boostrap_sampleNameChange.R"))
  source(paste0(pdir,"/polygR/phylogenetic_tree_with_boostrap_sampleNameChange_UPGMA.R"))
} else {
  source(paste0(pdir,"/polygR/phylogenetic_tree_with_boostrap.R"))
  source(paste0(pdir,"/polygR/phylogenetic_tree_with_boostrap_UPGMA.R"))
}

## purity_estimation

source(paste0(pdir,"/polygR/Purity_Estimation_for_polygR_w_distCutoff.R"))

## get angular distance trees
#if (sample_name_change) {
#    anno <- read.table(file.path(pdir,"AnnotationFiles",paste0(subject_name,"_annotationFile.txt")),sep="\t",header=T,stringsAsFactors = F)
#
#}

source(paste0(pdir,"/polygR/angular_dist_trees_w_root_allmarkers_averageReplicates_integrated.R"))
source(paste0(pdir,"/polygR/angular_dist_trees_w_root_usedmarkers_averageReplicates_integrated.R"))

source(paste0(pdir,"/polygR/angular_dist_trees_w_root_allmarkers_representativeReplicates_integrated.R"))
source(paste0(pdir,"/polygR/angular_dist_trees_w_root_usedmarkers_representativeReplicates_integrated.R"))
